server.port=${SERVER_PORT:8080}

spring.application.name=swissroute-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:swissroute_db}
spring.datasource.username=${DB_USER:swissroute_user}
spring.datasource.password=${DB_PASS:swissroute}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.key.private=${SECRET_KEY:dev-secret-key-group03}
security.jwt.user.generator=AUTH0JWT-BACKEND-GROUP03
security.jwt.expiration-ms=120000

transport.api.base-url=${TRANSPORT_API_BASE_URL:http://transport.opendata.ch/v1}